### ISSUE TITLE
Example CheckList

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-Entities#1]
- [ ] "_Dead End_"
- [ ] Inheritance
- [ ] Entity Namespace e.g. `haveibeenpwned.DataClass`

**Properties**
- [ ] Namespace e.g. `dynamic.emailAddress`
- [ ] Namespace e.g. `affiliation.profile-url`

**Comment by cmlh** [comment]
Fix #1
